server.error.include-message: always
spring:
  main.banner-mode: off
  output.ansi.enabled: always
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
  datasource:
    url: jdbc:postgresql://localhost:5432/tutio_db
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: none
    open-in-view: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
rabbitmq:
  exchange:
    events: 'tutio-events'
  queue:
    booking:
      booking-process-started: 'booking-process-started-events'
      booking-countdown-started: 'booking-countdown-started-events'
      time-for-booking-expired: 'time-for-booking-expired-events'
      plan-booking-requested: 'plan-booking-requested-events'
      booking-planned: 'booking-planned-events'
      booking-planning-rejected: 'booking-planning-rejected-events'
      meeting-cost-calculated: 'meeting-cost-calculated-events'
      booking-paid-successfully: 'booking-paid-successfully-events'
      booking-approved: 'booking-approved-events'
      booking-payment-failed: 'booking-payment-failed-events'
      booking-cancelled: 'booking-cancelled-events'
