spring.output.ansi.enabled: always
spring:
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
rabbitmq:
  exchange:
    events: 'tutio-events'
  queue:
    booking:
      booking-process-started: 'booking-process-started-events'
