name: CI

on:
  push:
  pull_request:
    paths:
      'server-app/**'
  workflow_dispatch:

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server-app/BookingService
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: server-app/BookingService/build/test-results/**/*.xml