name: CI

on:
  push:
    branches:
      - 'master'
      - 'develop'
    paths:
      'server-app/**'
  pull_request:
    paths:
      'server-app/**'
  workflow_dispatch:

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server-app/BookingService
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test